[package]
name = "ama_upow2"
version = "0.1.0"
edition = "2024"

[features]
default = ["blake3/default", "blake3/rayon"]
neon = ["blake3/neon"]
rayon = ["blake3/rayon"]

[dependencies]
bincode = "2.0.1"
blake3 = "1.0"
rand = "0.9.2"
once_cell = "1.21.3"
